# Generated by Django 2.1.4 on 2019-03-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20190303_0102'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='vip_store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_vip_store', to='stores.VipStore', verbose_name='Tienda VIP'),
        ),
    ]
