# Generated by Django 2.1.4 on 2019-03-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre producto')),
                ('content', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'producto basico',
                'verbose_name_plural': 'productos basicos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BasicStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre tienda')),
                ('content', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='stores', verbose_name='Imagen')),
                ('celphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Celular')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'tienda basica',
                'verbose_name_plural': 'tiendas basicas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo')),
                ('price', models.CharField(max_length=20, verbose_name='Precio')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='basicproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_basic_products', to='stores.BasicStore', verbose_name='Productos'),
        ),
    ]
