# Generated by Django 2.1.4 on 2019-03-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipCarruselIamge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'catalogo vip imagen',
                'verbose_name_plural': 'catalogo vip imagenes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VipCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'categoria vip',
                'verbose_name_plural': 'categorias vip',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VipProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre producto')),
                ('content', models.TextField(verbose_name='Descripcion')),
                ('price', models.CharField(max_length=20, verbose_name='Precio')),
                ('starts', models.PositiveSmallIntegerField(verbose_name='Estrellas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_vip_category', to='stores.VipCategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'producto vip',
                'verbose_name_plural': 'productos vip',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VipStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre tienda')),
                ('content', models.TextField(verbose_name='Descripcion')),
                ('celphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Celular')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'tienda vip',
                'verbose_name_plural': 'tiendas vip',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='vipproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_vip_products', to='stores.VipStore', verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='vipcarruseliamge',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_vip_images', to='stores.VipStore', verbose_name='Imagenes'),
        ),
    ]
